<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('arcanist', 'lint/engine/base');
phutil_require_module('arcanist', 'lint/linter/text');
phutil_require_module('arcanist', 'lint/severity');

phutil_require_module('phutil', 'filesystem');


phutil_require_source('JavaLintEngine.php');
