<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 * @generated
 * @phutil-library-version 2
 */

phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' =>
  array(
    'ArcJIRAConfiguration' => 'arcanist/ArcJIRAConfiguration.php',
    'CommitListener' => 'events/CommitListener.php',
    'JavaLintEngine' => 'lint/engine/JavaLintEngine.php',
  ),
  'function' =>
  array(
  ),
  'xmap' =>
  array(
    'ArcJIRAConfiguration' => 'ArcanistConfiguration',
    'CommitListener' => 'PhutilEventListener',
    'JavaLintEngine' => 'ArcanistLintEngine',
  ),
));
