<?php

/**
 * This file is automatically generated. Use 'phutil_mapper.php' to rebuild it.
 * @generated
 */

phutil_register_library_map(array(
  'class' =>
  array(
    'ArcJIRAConfiguration' => 'arcanist',
    'JavaLintEngine' => 'lint/engine',
  ),
  'function' =>
  array(
  ),
  'requires_class' =>
  array(
    'ArcJIRAConfiguration' => 'ArcanistConfiguration',
    'JavaLintEngine' => 'ArcanistLintEngine',
  ),
  'requires_interface' =>
  array(
  ),
));
