<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('arcanist', 'configuration');
phutil_require_module('arcanist', 'differential/commitmessage');
phutil_require_module('arcanist', 'parser/diff');
phutil_require_module('arcanist', 'parser/diff/changetype');


phutil_require_source('ArcJIRAConfiguration.php');
